// Generated by gencpp from file lerobot_ros/DrawingCompletedRequest.msg
// DO NOT EDIT!


#ifndef LEROBOT_ROS_MESSAGE_DRAWINGCOMPLETEDREQUEST_H
#define LEROBOT_ROS_MESSAGE_DRAWINGCOMPLETEDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lerobot_ros
{
template <class ContainerAllocator>
struct DrawingCompletedRequest_
{
  typedef DrawingCompletedRequest_<ContainerAllocator> Type;

  DrawingCompletedRequest_()
    {
    }
  DrawingCompletedRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DrawingCompletedRequest_

typedef ::lerobot_ros::DrawingCompletedRequest_<std::allocator<void> > DrawingCompletedRequest;

typedef boost::shared_ptr< ::lerobot_ros::DrawingCompletedRequest > DrawingCompletedRequestPtr;
typedef boost::shared_ptr< ::lerobot_ros::DrawingCompletedRequest const> DrawingCompletedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace lerobot_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lerobot_ros/DrawingCompletedRequest";
  }

  static const char* value(const ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrawingCompletedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::lerobot_ros::DrawingCompletedRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LEROBOT_ROS_MESSAGE_DRAWINGCOMPLETEDREQUEST_H
