// Generated by gencpp from file lerobot_ros/DrawingRequest.msg
// DO NOT EDIT!


#ifndef LEROBOT_ROS_MESSAGE_DRAWINGREQUEST_H
#define LEROBOT_ROS_MESSAGE_DRAWINGREQUEST_H

#include <ros/service_traits.h>


#include <lerobot_ros/DrawingRequestRequest.h>
#include <lerobot_ros/DrawingRequestResponse.h>


namespace lerobot_ros
{

struct DrawingRequest
{

typedef DrawingRequestRequest Request;
typedef DrawingRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DrawingRequest
} // namespace lerobot_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lerobot_ros::DrawingRequest > {
  static const char* value()
  {
    return "6fec06d56f8f2e4b65a60fc5e8f7a8f9";
  }

  static const char* value(const ::lerobot_ros::DrawingRequest&) { return value(); }
};

template<>
struct DataType< ::lerobot_ros::DrawingRequest > {
  static const char* value()
  {
    return "lerobot_ros/DrawingRequest";
  }

  static const char* value(const ::lerobot_ros::DrawingRequest&) { return value(); }
};


// service_traits::MD5Sum< ::lerobot_ros::DrawingRequestRequest> should match
// service_traits::MD5Sum< ::lerobot_ros::DrawingRequest >
template<>
struct MD5Sum< ::lerobot_ros::DrawingRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lerobot_ros::DrawingRequest >::value();
  }
  static const char* value(const ::lerobot_ros::DrawingRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lerobot_ros::DrawingRequestRequest> should match
// service_traits::DataType< ::lerobot_ros::DrawingRequest >
template<>
struct DataType< ::lerobot_ros::DrawingRequestRequest>
{
  static const char* value()
  {
    return DataType< ::lerobot_ros::DrawingRequest >::value();
  }
  static const char* value(const ::lerobot_ros::DrawingRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lerobot_ros::DrawingRequestResponse> should match
// service_traits::MD5Sum< ::lerobot_ros::DrawingRequest >
template<>
struct MD5Sum< ::lerobot_ros::DrawingRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lerobot_ros::DrawingRequest >::value();
  }
  static const char* value(const ::lerobot_ros::DrawingRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lerobot_ros::DrawingRequestResponse> should match
// service_traits::DataType< ::lerobot_ros::DrawingRequest >
template<>
struct DataType< ::lerobot_ros::DrawingRequestResponse>
{
  static const char* value()
  {
    return DataType< ::lerobot_ros::DrawingRequest >::value();
  }
  static const char* value(const ::lerobot_ros::DrawingRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEROBOT_ROS_MESSAGE_DRAWINGREQUEST_H
