(cl:defpackage lerobot_ros-srv
  (:use )
  (:export
   "DRAWINGCOMPLETED"
   "<DRAWINGCOMPLETED-REQUEST>"
   "DRAWINGCOMPLETED-REQUEST"
   "<DRAWINGCOMPLETED-RESPONSE>"
   "DRAWINGCOMPLETED-RESPONSE"
   "DRAWINGREQUEST"
   "<DRAWINGREQUEST-REQUEST>"
   "DRAWINGREQUEST-REQUEST"
   "<DRAWINGREQUEST-RESPONSE>"
   "DRAWINGREQUEST-RESPONSE"
  ))

